# [v0.13-pre (v3)] Spring Datasource (H2) 설정
spring:
  datasource:
    url: jdbc:h2:mem:pre_billing_db # (v0.12의 'testdb'와 DB 이름 분리)
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # [v0.13-pre] Batch Job 자동 실행 방지
  batch:
    job:
      enabled: false